name: Erlang CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}}
    strategy:
      fail-fast: false
      matrix:
        otp: [24.0.2, 23.2.1]
    steps:
    - uses: actions/checkout@v2
    - uses: gleam-lang/setup-erlang@v1.1.2
      with:
        otp-version: ${{matrix.otp}}
    - name: Compile
      run: rebar3 compile
    - name: Run dialyzer
      run: rebar3 dialyzer
    - name: Run xref
      run: rebar3 xref
    - name: Run elvis
      run: rebar3 as lint lint
    - name: Run eunit
      run: rebar3 eunit
